---
fixtures:
  repositories:
    apache: https://github.com/puppetlabs/puppetlabs-apache.git
    archive: https://github.com/voxpupuli/puppet-archive.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    cron_core: https://github.com/puppetlabs/puppetlabs-cron_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
